### ISSUE TITLE
Boring resource names generated by the converter

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-converter-terraform#147]
### What happened?

@thomas11 points out that rolling out the converter to providers generated diffs such as this one:

```
  - ///     var exampleGit = new AzureDevOps.Git("exampleGit", new()
  + ///     var exampleGit = new AzureDevOps.Git("example", new()
```

Notice that the name selected the resource is now "example" which is more boring than "exampleGit", and several resources are now all named "example". Granted, the original HCL also has lots of resources named "example", but we use to provide this little enhancement and now do not anymore.

There is no impact on validity, only aesthetics.

### Example

```terraform
resource "azuredevops_project" "example" {
  name = "Example Project"
}

resource "azuredevops_git_repository" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Repository"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_build_definition" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Build Definition"

  repository {
    repo_type = "TfsGit"
    repo_id   = azuredevops_git_repository.example.id
    yml_path  = "azure-pipelines.yml"
  }
}

resource "azuredevops_branch_policy_build_validation" "example" {
  project_id = azuredevops_project.example.id

  enabled  = true
  blocking = true

  settings {
    display_name        = "Example build validation policy"
    build_definition_id = azuredevops_build_definition.example.id
    valid_duration      = 720
    filename_patterns = [
      "/WebApp/*",
      "!/WebApp/Tests/*",
      "*.cs"
    ]

    scope {
      repository_id  = azuredevops_git_repository.example.id
      repository_ref = azuredevops_git_repository.example.default_branch
      match_type     = "Exact"
    }

    scope {
      repository_id  = azuredevops_git_repository.example.id
      repository_ref = "refs/heads/releases"
      match_type     = "Prefix"
    }
    
    scope {
      match_type     = "DefaultBranch"
    }
  }
}

```

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I'd argue this is by design. We make the resource logical name match the terraform name.

**Comment by t0yv0** [comment]
Yeah. Feel free to close.

**Comment by t0yv0** [comment]
By aesthetics I just mean it doesn't affect `pulumi up` breaking. I see your POV but TF could do this as well (where examples are coming from). I get a sense that if you want to put time in to contribute a fix here Justin's team may be amenable - I'm sorry for writing "feel free to close" I guess I just don't feel as strongly about this one, should have let you write the ticket.

**Comment by t0yv0** [comment]
Yeah this kind of feature if we did it would need to be opt-in for documentation use case only.
