### ISSUE TITLE
Support tfstate conversion

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-converter-terraform#23]
This converter plugin currently supports converting a Terraform program into a Pulumi program, but does not yet support converting a `.tfstate` file to a Pulumi state file.  We would like to support both of these in the coverter.

This is dependent on adding the user interface to `pulumi import` and `pulumi convert` to leverage this as part of https://github.com/pulumi/pulumi/issues/5953#issuecomment-1688602915.

**Comment by Frassle** [comment]
This is now supported, the 3.87.0 release of the cli put in the last main parts of this.
