### ISSUE TITLE
Correct pulumi package is not listed for GCP projects

### ISSUE THREAD

**Issue by zshareef** [pulumi/pulumi-converter-terraform#38]
### What happened?

When I am converting an GCP terraform project to Pulumi Typescript, then the initial line to import the gcp packages is not correct.
In correct form, it should be 
`import * as gcp from '@pulumi/gcp';`

But when I am using pulumi converter then I get the following:
`import * as gcp from '@pulumi/google';`

### Example

When converting the GCP terraform project for pulumi TypeScript, the correct format to import the GCP package should be following:

`import * as gcp from '@pulumi/gcp';`

But we are getting the following using the converter:

`import * as gcp from '@pulumi/google';`

### Output of `pulumi about`

pulumi==3.73.0
pulumi-aws==5.41.0
pulumi-eks==1.0.2
pulumi-gcp==6.62.0
pulumi-kubernetes==3.30.0
pulumi-random==4.13.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I suspect this is the same root cause as https://github.com/pulumi/pulumi-converter-terraform/issues/39. Getting a fix in place now.
