### ISSUE TITLE
Attempt state conversion without mapping files

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-converter-terraform#41]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

If we fail to get mapping information in the state converter currently we just error out (e.g. see https://github.com/pulumi/pulumi-converter-terraform/issues/39).

But we could instead still do a best effort guess of the type tokens and import string. `pulumi import` doesn't need perfect data to start because it will write out the import file generated if the import itself fails to allow for manual fix up.

**Comment by GeoffMillerAZ** [comment]
related issue: #42

**Comment by GeoffMillerAZ** [comment]
+1 on this feature. There are bound to be cases where Terraform resources exist, and their equivalent is not needed in Pulumi. There may also be cases where an equivalent doesn't yet exist. In each case, the import should proceed after an affirmative prompt from the user. The prompt can include what resources will be imported and what will not. The user can then decide if they want to continue, and if they do continue, they know what problems they need to solve in the conversion.
