### ISSUE TITLE
HCL splats cannot be converted

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-converter-terraform#57]
The following HCL code causes a panic (which has a deferred recover, so it's not like the bridge dies) due to the presence of a splat `.*.` in the HCL:

```hcl
resource "aws_worklink_fleet" "example" {
  name = "terraform-example"

  network {
    vpc_id             = aws_vpc.test.id
    subnet_ids         = [aws_subnet.test.*.id]
    security_group_ids = [aws_security_group.test.id]
  }
}
```

This causes the example to get dropped for all languages.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/worklink/fleet.py#L371 yes there is the example now.
