### ISSUE TITLE
Add support for `replace` built-in function

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-converter-terraform#90]
`replace` was originally missing from the `pulumi-std` schema, but that's since been addressed with https://github.com/pulumi/pulumi-std/pull/12

But the converter still isn't using it:

https://github.com/pulumi/pulumi-converter-terraform/blob/a7863a7a3c0bf2e151a4910cc232614abf4c0fec/pkg/convert/tf.go#L636-L641

Looks like the test will need to be updated as well, as the following diagnostics should go away:

https://github.com/pulumi/pulumi-converter-terraform/blob/a7863a7a3c0bf2e151a4910cc232614abf4c0fec/pkg/convert/testdata/programs/builtin_functions/pcl/diagnostics.json#L88-L89

**Comment by Frassle** [comment]
5 minute job
